### ISSUE TITLE
Use bundle cache

### ISSUE THREAD

**Issue by HoloPollock** [joshlarsen/jekyll4-deploy-gh-pages#1]
is there a way to use a bundle cache to speed up builds

something like this instead of just bundle

    bundle config path vendor/bundle
    bundle install --jobs 4 --retry 3

add tell people to add
- uses: actions/cache@v1
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-

before the build if they want to use a cache

**Comment by HoloPollock** [comment]
if you do this It seems to break the ability to run the jekyll command. Honestly Im a noob at this stuff not sure why

**Comment by joshlarsen** [comment]
@HoloPollock this is a good suggestion and an easy fix. Will update shortly.
