### ISSUE TITLE
including ruby-lsp in dev section of Gemfile causes error because requires Ruby (>= 2.7.3)

### ISSUE THREAD

**Issue by stepheneb** [joshlarsen/jekyll4-deploy-gh-pages#15]
Have been including `ruby-lsp` in dev section of gem file for Ruby projects (for better dev experience in vscode along with associated extension) and got this error using the action when adding it to a Jekyll project.

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    ruby-lsp (~> 0.3.5) was resolved to 0.3.5, which depends on
      Ruby (>= 2.7.3)

  Current Ruby version:
    Ruby (= 2.6.6)
```

**Comment by numberisnan** [comment]
If anyone else has this issue, I just forked the repo and added '-v 2.4.22' to the Dockerfile as the error message recommended.
