### ISSUE TITLE
bump ruby to 2.7?

### ISSUE THREAD

**Issue by duncdrum** [joshlarsen/jekyll4-deploy-gh-pages#4]
after initial success using the workflow, and publishing the site, on subsequent commits to `master` i get 

```
Building Jekyll site...
43
/github/workspace/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f8099fe3e65
44
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
45
- Control frame information -----------------------------------------------
47
c:0037 p:---- s:0193 e:000192 CFUNC  :open
48
c:0036 p:0022 s:0187 e:000186 BLOCK  /github/workspace/vendor/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi/library.rb:112 [FINISH]
…

[NOTE]
942
You may have encountered a bug in the Ruby interpreter or extension libraries.
943
Bug reports are welcome.
944
For details: https://www.ruby-lang.org/bugreport.html
```

not sure what's going on, but maybe a bump do the docker image can help?

**Comment by joshlarsen** [comment]
Can you share your `Gemfile`? It looks like there are a few reports of certain gems causing that error (e.g. [here](https://github.com/sass/sassc-ruby/issues/146)).

**Comment by duncdrum** [comment]
sure, I had some time to play around, and the failures seem to occur completely at random.

rerunning the workflow task usually succeeds. 
```
source "https://rubygems.org"
gemspec
```

and

```
# coding: utf-8

Gem::Specification.new do |spec|
  spec.name          = "forty_jekyll_theme"
  spec.version       = "1.2"
  spec.authors       = ["Andrew Banchich"]
  spec.email         = ["andrewbanchich@gmail.com"]

  spec.summary       = %q{A Jekyll version of the "Forty" theme by HTML5 UP.}
  spec.homepage      = "https://gitlab.com/andrewbanchich/forty-jekyll-theme"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").select { |f| f.match(%r{^(assets|_layouts|_includes|_sass|LICENSE|README)}i) }

  spec.add_development_dependency "jekyll", "~> 4.0"
  spec.add_development_dependency "bundler", "~> 2.1"
end
```

**Comment by joshlarsen** [comment]
Strange, not sure what is going on. That thread I linked to has quite a few cases of people having similar issues. You might want to check [this](https://github.com/sass/sassc-ruby/issues/146#issuecomment-534197168) out.

Maybe manually specify `sassc` version `2.1.0`.

**Comment by joshlarsen** [comment]
Strange, not sure what is going on. That thread I linked to has quite a few cases of people having similar issues. You might want to check [this](https://github.com/sass/sassc-ruby/issues/146#issuecomment-534197168) out.

Maybe manually specify `sassc` version `2.1.0`.

**Comment by duncdrum** [comment]
Ok those links are certainly helpful, thank you for pointing me there. I still don't fully grasp why this would fail at random, or exactly why its failing,…… but my working knowledge of both ruby and Gh-Actions is limited. 

I ll keep this issue open until i had a bit more time to dig into this.

**Comment by joshlarsen** [comment]
@duncdrum I started getting the `[BUG] Illegal instruction` error during builds. I have pushed a new version of the action that may fix it. It seems to be working for me. Let me know if you are able to test it.

**Comment by duncdrum** [comment]
@joshlarsen i haven't been able to get the error to trigger, so your fix seems to have worked.

**Comment by joshlarsen** [comment]
Good to hear. Thanks.
