### ISSUE TITLE
Job cleanup warning: tar permissions error

### ISSUE THREAD

**Issue by theshteves** [joshlarsen/jekyll4-deploy-gh-pages#7]
Is this just me?

![tar-permissions-warning](https://user-images.githubusercontent.com/3631807/102850444-7dae1880-43e7-11eb-8bd3-0c1a1c4f70a3.png)

**Comment by joshlarsen** [comment]
Maybe an issue with `nokogumbo`? Bundler cache seems to be working ok for me.

<img width="794" alt="CleanShot 2020-12-22 at 09 59 53@2x" src="https://user-images.githubusercontent.com/2565382/102902090-76652a00-443c-11eb-87ee-1263d088a229.png">
